import React from "react";
import { Box, HStack } from "@chakra-ui/react";
import { ModalDetails } from "../components/ModalDetails";

export const TableRow = ({
  fechaSolicitado,
  nombreItem,
  um,
  cantidad,
  fechaRequerido,
  estadoPedido,
  recibido,
}) => {
  return (
    <HStack ml={5} px={1} border="1px">
      <Box
        fontWeight="bold"
        fontSize="12px"
        color="gray.600"
        w="10%"
        borderRight="1px"
        paddingLeft="10px"
        py="5px"
      >
        {fechaSolicitado}
      </Box>
      <Box
        fontWeight="bold"
        fontSize="12px"
        color="gray.600"
        w="25%"
        borderRight="1px"
        paddingLeft="10px"
        py="5px"
      >
        {nombreItem}
      </Box>
      <Box
        fontWeight="bold"
        fontSize="12px"
        color="gray.600"
        w="7%"
        paddingLeft="10px"
        borderRight="1px"
        py="5px"
      >
        {um}
      </Box>
      <Box
        fontWeight="bold"
        fontSize="12px"
        color="gray.600"
        w="7%"
        borderRight="1px"
        paddingLeft="10px"
        py="5px"
      >
        {cantidad}
      </Box>
      <Box
        fontWeight="bold"
        fontSize="12px"
        color="gray.600"
        w="10%"
        borderRight="1px"
        paddingLeft="10px"
        py="5px"
      >
        Mabel
      </Box>
      <Box
        fontWeight="bold"
        fontSize="12px"
        color="gray.600"
        w="10%"
        paddingLeft="10px"
        borderRight="1px"
        py="5px"
      >
        {fechaRequerido}
      </Box>
      <Box
        fontWeight="bold"
        fontSize="12px"
        color="gray.600"
        w="15%"
        borderRight="1px"
        paddingLeft="10px"
        py="5px"
      >
        {estadoPedido}
      </Box>
      <Box
        fontWeight="bold"
        fontSize="12px"
        color="gray.600"
        w="7%"
        borderRight="1px"
        paddingLeft="10px"
        py="5px"
      >
        {recibido}
      </Box>
      <Box
        fontWeight="bold"
        fontSize="12px"
        color="gray.600"
        w="12%"
        paddingLeft="10px"
        py="5px"
      >
        <ModalDetails
          fechaSolicitado={fechaSolicitado}
          nombreItem={nombreItem}
          um={um}
          cantidad={cantidad}
          fechaRequerido={fechaRequerido}
          estadoPedido={estadoPedido}
          recibido={recibido}
        />
      </Box>
    </HStack>
  );
};
